export const S = {
    stage: null, mapLayer: null, paintLayer: null, drawLayer: null, cursorLayer: null,
    W: 0, H: 0, mapDisplayW: 0, mapDisplayH: 0,
    eraserShape: null, transformer: null, imgCache: {},
    currentTool: 'select', placeMode: localStorage.getItem('boardPlaceMode') || 'click',
    _isPanning: false, _panStart: null, _panOrigin: null,
    eraseMode: false, currentColor: '#df5840', currentWidth: 2,
    currentLineStyle: 'solid', currentFill: true, currentBelowMap: false, currentArrowTip: false,
    currentTextFont: 'Inter', currentTextSize: 20, currentTextBold: false, currentTextItalic: false,
    currentTextOpacity: 1, currentTextAlign: 'left', currentTextShadow: false,
    currentTextBg: false, currentTextBgColor: '#0c0e14', currentTextBgOpacity: 0.72, currentTextRadius: 14,
    currentTextBorder: false, currentTextBorderColor: '#ffffff',
    currentTextStroke: false, currentTextStrokeColor: '#000000',
    currentOpacity: 1, _activeTextInput: null, currentSide: 'atk',
    selectedAgent: null, selectedAbility: null, _lastMapValue: null, currentAoeType: 'circle',
    boardMoments: [], activeMomentId: null,
    _undoStack: [], _redoStack: [], _eraseBuffer: null,
    isDrawing: false, isAbilityDrag: false, abilityDragPreview: null,
    startPos: null, lastMousePos: { x:0, y:0 },
    currentShape: null, pencilPts: [], movePts: [],
    currentMultiSubTool: 'vision', _vCenterX: 0, _vCenterY: 0,
    currentVisionPreset: 'normal', visionConeAngle: 0,
    _visionData: null, _mapAlphaFull: null, _visionScale: 1,
    currentMoveSpeed: 'rifle-run', currentMoveDash: false,
    agents: [], maps: [],
    _restoring: false,
    _lastPlaceTime: 0, _mouseDownTime: 0, _mouseDownPos: null, _isDragMove: false,
    _selectedShape: null,
    agentFilter: 'all', currentStratId: null,
    agentIconScale: 1.0, abilityIconScale: 1.0, iconBgOpacity: 1.0,
    keybinds: {}, _listeningFor: null,
    currentIconKey: 'pin', _mapDisplayRot: 0,
    _dndPreview: null, _mouseDrag: null, _dndStartX: 0, _dndStartY: 0, _dndHasMoved: false,
    _dragInputEl: null, _dragStartX: 0, _dragStartVal: 0, _dragActive: false, _dragCb: null,
    _optsPanelTimer: null, _prevPanelTool: null,
    _isEraserDown: false, _aoeHiddenMap: {},
};
